const brandsConfig={ 
    PG:{
    BWINCOM:{
        frontendid:'bz',
        BrandId:'BWINCOM',
        Country:'GB',
        ip:'10.151.147.111'
    },
    PARTYPOKER:{
        frontendid:'pp',
        BrandId:'PARTYPOKER',
        Country:'GB',
        ip:'10.151.147.111'
    }},
    LCG:{
    LADBROKEUK:{
        frontendid:'ld',
        BrandId:'LADBROKEUK',
        Country:'GB',
        ip:'212.159.25.210'
    },
    CORAL:{
        frontendid:'cl',
        BrandId:'CORAL',
        Country:'GB',
        ip:'212.159.25.210'
    },
    }
}
module.exports=brandsConfig;